services:
  democratic-linux:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - vm-data:/app/vm
    privileged: true
    restart: on-failure:3
    dns:
      - 192.168.253.2
    environment:
      - PORT=3000
      - QEMU_MEM=512M
      - QEMU_CPUS=1

volumes:
  vm-data:
